### ISSUE TITLE
ArcDPS evtc combat bindings seem to not be in real time

### ISSUE THREAD

**Issue by meepoSenpai** [Zerthox/arcdps-rs#13]
Hey, it seems that the evtc `RawCombatCallback` for area combat seems to be working with a 3-4 second delay in comparison to the information that's input into arcDPS. The `RawCombatCallback` for `combat_local` seems to be in (more or less) realtime. I'm not entirely sure if this is working as intended, or if I'm using the library wrong.

**Comment by Zerthox** [comment]
The bindings don't have anything do with this. It's an intentional delay on Arc's side to prevent abuse.
